// ============================================================================
// TINY ESCAPE ROOM — the rules, with no rendering and no clock in them.
//
// Three locks, two to five minutes, and every one of them solvable with the
// screen muted and the network off. That is not a nicety: this is a room drawn
// in SVG with tones generated by the Web Audio API, because egress is the
// scarcest resource in this app (5 GB/month, and media is the whole bill) and
// a game is not worth a single downloaded byte. Nothing here loads an asset,
// and nothing here can.
//
// Everything is pure and takes its randomness as an argument, for the reason
// runner.js and geo.js do: an animation-driven feature is otherwise
// untestable, and "the third lock is unopenable with this seed" is exactly the
// bug that ships. `createRoom(rand)` with a stub rand gives a fixed room, so
// tests/escape-room.test.js walks a whole solve, and walks the wrong answers
// too.
//
// The chain, which is the design:
//   1. THE PICTURE. Four objects in the room, each marked with a shape. A
//      framed picture on the wall shows those shapes in an order. Tap the
//      objects in the picture's order. → the drawer opens, and there is a
//      chime in it.
//   2. THE CHIME. Three bells. The chime plays a four-note phrase; play it
//      back. Each bell also FLASHES as it sounds, so the whole lock works
//      with the volume off — sound is a second channel here, never the only
//      one. → a folded slip, naming three of the room's objects in an order.
//   3. THE LOCK. Three dials. Each object has carried a number in plain sight
//      since the first second of the run; the slip says which order they go
//      in. → the door.
//
// No penalties anywhere. A wrong tap clears the attempt and says so; a wrong
// code leaves the dials exactly where they were, because re-entering three
// digits you already chose is a punishment with no lesson in it. There is no
// attempt limit, no countdown, and no score. After a few misses on a lock,
// `hintFor` offers a nudge — the failure mode of a two-minute game is being
// stuck, not being insufficiently challenged.
// ============================================================================

export const OBJECTS = ['lamp', 'clock', 'plant', 'book']
export const SHAPES = ['circle', 'square', 'triangle', 'diamond']
export const BELL_COUNT = 3
export const PHRASE_LENGTH = 4
export const CODE_LENGTH = 3

// The three objects that carry a number. The lamp does not — it is the one
// that is only ever a shape, so the first lock and the last are not the same
// set of things looked at twice.
export const NUMBERED = ['clock', 'plant', 'book']

export const OBJECT_LABEL = {
  lamp: 'the lamp',
  clock: 'the clock',
  plant: 'the plant',
  book: 'the book',
}

/** What each object's number IS, so the room can label it honestly. */
export const NUMBER_LABEL = {
  clock: 'the hour on its face',
  plant: 'the leaves on it',
  book: 'the page it is open at',
}

export const STAGES = ['picture', 'chime', 'lock', 'out']

const MISSES_BEFORE_HINT = 3

function shuffle(list, rand) {
  const out = [...list]
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

/**
 * A fresh room. `rand` is injectable, so a test gets the same room every time
 * and the app gets a different one on every "Again" — which is the whole of
 * the replayability: 4! shape assignments × 4! picture orders × 3⁴ phrases ×
 * 9³ numbers × 3! code orders.
 */
export function createRoom(rand = Math.random) {
  const assigned = shuffle(SHAPES, rand)
  const shapes = {}
  OBJECTS.forEach((id, i) => {
    shapes[id] = assigned[i]
  })

  const phrase = []
  for (let i = 0; i < PHRASE_LENGTH; i++) phrase.push(Math.floor(rand() * BELL_COUNT))
  // A phrase of one repeated note is a phrase nobody can get wrong, which is
  // not a lock. Nudged rather than re-rolled: a retry loop on an injected rand
  // is a test that hangs.
  if (phrase.every((n) => n === phrase[0])) {
    phrase[PHRASE_LENGTH - 1] = (phrase[0] + 1) % BELL_COUNT
  }

  const numbers = {}
  for (const id of NUMBERED) numbers[id] = 1 + Math.floor(rand() * 9)

  return {
    shapes,
    order: shuffle(SHAPES, rand),
    phrase,
    numbers,
    codeOrder: shuffle(NUMBERED, rand),
    tapped: [],
    heard: [],
    dials: Array(CODE_LENGTH).fill(0),
    stage: 0,
    // 'wrong' is shown and then cleared by the component; it is state rather
    // than a callback so the whole room stays a value.
    feedback: null,
    misses: [0, 0, 0],
  }
}

/** The three digits the lock wants, in order. */
export function answerCode(room) {
  return room.codeOrder.map((id) => room.numbers[id])
}

export const isSolved = (room) => room.stage === 3

function miss(room) {
  const misses = [...room.misses]
  misses[room.stage] += 1
  return misses
}

/* --------------------------------------------------------------------------
   Lock 1 — tap the objects in the picture's shape order.
   -------------------------------------------------------------------------- */
export function tapObject(room, id) {
  if (room.stage !== 0 || !OBJECTS.includes(id)) return room
  const want = room.order[room.tapped.length]
  if (room.shapes[id] !== want) {
    return { ...room, tapped: [], feedback: 'wrong', misses: miss(room) }
  }
  const tapped = [...room.tapped, id]
  if (tapped.length === room.order.length) {
    return { ...room, tapped, stage: 1, feedback: 'opened' }
  }
  return { ...room, tapped, feedback: 'ok' }
}

/* --------------------------------------------------------------------------
   Lock 2 — play the phrase back.
   -------------------------------------------------------------------------- */
export function tapBell(room, i) {
  if (room.stage !== 1 || !Number.isInteger(i) || i < 0 || i >= BELL_COUNT) return room
  if (room.phrase[room.heard.length] !== i) {
    return { ...room, heard: [], feedback: 'wrong', misses: miss(room) }
  }
  const heard = [...room.heard, i]
  if (heard.length === room.phrase.length) {
    return { ...room, heard, stage: 2, feedback: 'opened' }
  }
  return { ...room, heard, feedback: 'ok' }
}

/* --------------------------------------------------------------------------
   Lock 3 — three dials.

   A wrong code leaves the dials alone. Wiping them would mean re-entering
   digits the player already decided on, which teaches nothing and is the
   single most common way a small puzzle becomes annoying.
   -------------------------------------------------------------------------- */
export function setDial(room, slot, value) {
  if (room.stage !== 2) return room
  if (!Number.isInteger(slot) || slot < 0 || slot >= CODE_LENGTH) return room
  const dials = [...room.dials]
  dials[slot] = ((Math.trunc(value) % 10) + 10) % 10
  return { ...room, dials, feedback: null }
}

export function nudgeDial(room, slot, by) {
  if (room.stage !== 2) return room
  if (!Number.isInteger(slot) || slot < 0 || slot >= CODE_LENGTH) return room
  return setDial(room, slot, room.dials[slot] + by)
}

export function submitCode(room) {
  if (room.stage !== 2) return room
  const want = answerCode(room)
  if (room.dials.every((d, i) => d === want[i])) {
    return { ...room, stage: 3, feedback: 'opened' }
  }
  return { ...room, feedback: 'wrong', misses: miss(room) }
}

export function clearFeedback(room) {
  return room.feedback === null ? room : { ...room, feedback: null }
}

/* --------------------------------------------------------------------------
   Being stuck.

   A nudge appears after a few misses on the lock you are actually on, and it
   is a nudge rather than the answer — where to look, not what to type. It is
   not earned, not spent, and it never mentions how many times you got it
   wrong. There is no cost to being stuck for a minute in a game that is over
   in five.
   -------------------------------------------------------------------------- */
export function hintFor(room) {
  if (isSolved(room)) return null
  if (room.misses[room.stage] < MISSES_BEFORE_HINT) return null
  if (room.stage === 0) return 'The picture on the wall is the order. The shapes are on the things.'
  if (room.stage === 1) return 'Play it again and watch which bell lights, not which one sounds.'
  return `The slip reads: ${room.codeOrder.map((id) => OBJECT_LABEL[id]).join(', then ')}.`
}

/** A neutral, unranked statement of fact for the end card. */
export function timeLabel(ms) {
  const total = Math.max(0, Math.round((ms || 0) / 1000))
  const m = Math.floor(total / 60)
  const s = total % 60
  if (m === 0) return `${s}s`
  return `${m}m ${String(s).padStart(2, '0')}s`
}
